name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_ralat_python
      id: test_ralat_python
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 12
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RALAT_PYTHON_RESULTS: "${{steps.test_ralat_python.outputs.result}}"
      with:
        runners: test_ralat_python
